version: '3.8'

services:
  web:
    build: .
    command: python /usr/src/app/manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=True
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
